### ISSUE TITLE
[BUG] data-group conversions empty or errors using f5-chariot on Windows

### ISSUE THREAD

**Issue by DumpySquare** [f5devcentral/f5-as3-config-converter#28]
## high level problem

When converting ``string`` and ``ip`` type ``data-groups``, records do not get converted.

Converting ``integer`` type ``data-group`` results in a runtime error.

TMOS version: 14.1
ACC version: 1.12.0

 ---

### TMOS configs

```
ltm data-group internal /partition_1/string-datagroup {
    records {
        /api/test/app1 {}
    }
    type string
}
ltm data-group internal /partition_2/address_datagroup {
    records {
        1.1.1.1/28 {
            data /
        }
        2.2.2.2/32 {
            data /
        }
        3.3.3.3/24 {
            data /
        }
    type ip
    }
}
```

### ACC output

```
{
    "class": "ADC",
    "schemaVersion": "3.27.0",
    "id": "urn:uuid:f8a2be46-d0b0-4451-8e5f-241cd1d1ac4a",
    "label": "Converted Declaration",
    "remark": "Auto-generated by AS3 Config Converter",
    "partition_1": {
        "class": "Tenant",
        "Shared": {
            "class": "Application",
            "template": "shared",
            "string-datagroup": {
                "records": [
                    {
                        "key": "0",
                        "value": ""
                    }
                ],
                "keyDataType": "string",
                "class": "Data_Group"
            }
        }
    },
    "partition_2": {
        "class": "Tenant",
        "Shared": {
            "class": "Application",
            "template": "shared",
            "address_datagroup": {
                "records": [
                    {
                        "key": "0",
                        "value": ""
                    }
                ],
                "keyDataType": "ip",
                "class": "Data_Group"
            }
        }
    }
}
```

### ACC logs

```
[2021-05-25T12:55:25.716Z] [INFO]: ACC METADATA {
  recognized: {
    'ltm data-group internal /partition_1/string-datagroup': { records: '{', '/api/test/app1': {}, '}': '', type: 'string' },
    'ltm data-group internal /partition_2/address_datagroup': { records: '{', type: 'ip', '}': '' }
  },
  supported: {
    'ltm data-group internal /partition_1/string-datagroup': { records: '{', '/api/test/app1': {}, '}': '', type: 'string' },
    'ltm data-group internal /partition_2/address_datagroup': { records: '{', type: 'ip', '}': '' }
  },
  unSupported: {},
  declarationInfo: {
    classes: { Data_Group: 2 },
    maps: {
      applications: [ '/partition_1/Shared', '/partition_2/Shared' ],
      objects: [
        '/partition_1/Shared/string-datagroup',
        '/partition_2/Shared/address_datagroup'
      ],
      tenants: [ '/partition_1', '/partition_2' ]
    },
    total: 2
  }
}
[2021-05-25T13:05:19.198Z] [INFO]: f5.chariot.convert called
[2021-05-25T13:05:19.198Z] [INFO]: f5.chariot.convert text found
[2021-05-25T13:05:19.850Z] [INFO]: ACC METADATA {
  recognized: {
    'ltm data-group internal /partition_1/string-datagroup': {
      records: '{',
      '/api/test/app1': {},
      'data "something in quotes with special stuff!@#$': {},
      '}': '',
      type: 'string'
    },
    'ltm data-group internal /partition_2/address_datagroup': {
      records: '{',
      'data "some data with special !@#$': {},
      type: 'ip',
      '}': ''
    }
  },
  supported: {
    'ltm data-group internal /partition_1/string-datagroup': {
      records: '{',
      '/api/test/app1': {},
      'data "something in quotes with special stuff!@#$': {},
      '}': '',
      type: 'string'
    },
    'ltm data-group internal /partition_2/address_datagroup': {
      records: '{',
      'data "some data with special !@#$': {},
      type: 'ip',
      '}': ''
    }
  },
  unSupported: {},
  declarationInfo: {
    classes: { Data_Group: 2 },
    maps: {
      applications: [ '/partition_1/Shared', '/partition_2/Shared' ],
      objects: [
        '/partition_1/Shared/string-datagroup',
        '/partition_2/Shared/address_datagroup'
      ],
      tenants: [ '/partition_1', '/partition_2' ]
    },
    total: 2
  }
}
```

---

### tmos config

```
ltm data-group internal integer_datagroup {
    records {
        1 {
            data 1
        }
        4 {
            data xxx
        }
        5 {
            data 5000
        }
        777 {
            data 7
        }
        96789 {
            data "some data with special !@#${}[]12345"
        }
    }
    type integer
}
```

### error message from log

```log
[2021-05-25T13:10:06.693Z] [INFO]: f5.chariot.convert called
[2021-05-25T13:10:06.693Z] [INFO]: f5.chariot.convert text found
[2021-05-25T13:10:06.694Z] [ERROR]: f5.chariot.convert failed with [TypeError: Cannot read property 'endsWith' of undefined
	at module.exports (c:\Users\bgordon\.vscode\extensions\f5devcentral.vscode-f5-chariot-1.12.0\node_modules\f5-as3-config-converter\src\util\convert\findLocation.js:33:24)
	at module.exports (c:\Users\bgordon\.vscode\extensions\f5devcentral.vscode-f5-chariot-1.12.0\node_modules\f5-as3-config-converter\src\removeIapp.js:27:21)
	at Object.acc (c:\Users\bgordon\.vscode\extensions\f5devcentral.vscode-f5-chariot-1.12.0\out\accWrapper.js:68:28)
	at c:\Users\bgordon\.vscode\extensions\f5devcentral.vscode-f5-chariot-1.12.0\out\extension.js:72:70
	at runMicrotasks (<anonymous>)
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async c:\Users\bgordon\.vscode\extensions\f5devcentral.vscode-f5-chariot-1.12.0\out\extension.js:69:13]
```

---

## expected

string, ip and integer data-groups should not produce error and get the appropriate records as indicated in the source

### example string data-group as as3 object
```
            "string-datagroup": {
                "records": [
                    {
                        "key": "/api/test/app1",
                        "value": ""
                    },
                    {
                        "key": "/api/test/app2",
                        "value": "something"
                    },
                    {
                        "key": "/api/test/app3",
                        "value": "something in quotes with special stuff!@#${}[]"
                    },
                    {
                        "key": "/api/test/app4",
                        "value": "1234x5678"
                    }
                ],
                "keyDataType": "string",
                "class": "Data_Group"
            }
```

**Comment by DumpySquare** [comment]
So, this may be a different problem.  i was able to get this working for string/ip datagroups.  

However, two things to note:
- this was on a linux machine (running vscode/acc-chariot extension)
  - windows produces the empty data-groups above (running vscode/acc-chariot extension)
- still doesn't seem to like bracket in the data

### input
```
ltm data-group internal /partition_1/string-datagroup {
    records {
        /api/test/app1 {}
        /api/test/app2 { 
            data something
        }
        /api/test/app3 { 
            data "something in quotes with special stuff!@#${}[]"
        }
        /api/test/app4 { 
            data 1234x5678
        }
    }
    type string
}
ltm data-group internal /partition_2/address_datagroup {
    records {
        1.1.1.1/28 {
            data somedata
        }
        2.2.2.2/32 {
            data "some data with special !@#${}[]12345"
        }
        3.3.3.3/24 {
            data 6534cv
        }
    type ip
    }
}
```
### output
```
{
    "class": "ADC",
    "schemaVersion": "3.27.0",
    "id": "urn:uuid:95892fbc-8a68-447d-9ed2-52bc1d287ab1",
    "label": "Converted Declaration",
    "remark": "Auto-generated by AS3 Config Converter",
    "partition_1": {
        "class": "Tenant",
        "Shared": {
            "class": "Application",
            "template": "shared",
            "string-datagroup": {
                "records": [
                    {
                        "key": "/api/test/app1",
                        "value": ""
                    },
                    {
                        "key": "/api/test/app2",
                        "value": ""
                    },
                    {
                        "key": "}",
                        "value": ""
                    },
                    {
                        "key": "/api/test/app3",
                        "value": ""
                    },
                    {
                        "key": "data \"something in quotes with special stuff!@#$",
                        "value": ""
                    },
                    {
                        "key": "/api/test/app4",
                        "value": ""
                    }
                ],
                "keyDataType": "string",
                "class": "Data_Group"
            }
        }
    },
    "partition_2": {
        "class": "Tenant",
        "Shared": {
            "class": "Application",
            "template": "shared",
            "address_datagroup": {
                "records": [
                    {
                        "key": "1.1.1.1/28",
                        "value": "somedata"
                    },
                    {
                        "key": "2.2.2.2/32",
                        "value": ""
                    },
                    {
                        "key": "3.3.3.3/24",
                        "value": "6534cv"
                    }
                ],
                "class": "Data_Group",
                "keyDataType": "string"
            }
        }
    }
}
```


## integer data-group still fails with runtime error
### input
```
ltm data-group internal integer_datagroup {
    records {
        1 {
            data 1
        }
        4 {
            data xxx
        }
        5 {
            data 5000
        }
        777 {
            data 7
        }
        96789 {
            data "some data with special !@#${}[]12345"
        }
    }
    type integer
}
```
### output
```
[2021-05-25T19:40:43.485Z] [INFO]: f5.chariot.convert called
[2021-05-25T19:40:43.485Z] [INFO]: f5.chariot.convert text found
[2021-05-25T19:40:43.487Z] [ERROR]: f5.chariot.convert failed with [TypeError: Cannot read property 'endsWith' of undefined
	at module.exports (/home/ted/.vscode-server/extensions/f5devcentral.vscode-f5-chariot-1.12.0/node_modules/f5-as3-config-converter/src/util/convert/findLocation.js:33:24)
	at module.exports (/home/ted/.vscode-server/extensions/f5devcentral.vscode-f5-chariot-1.12.0/node_modules/f5-as3-config-converter/src/removeIapp.js:27:21)
	at Object.acc (/home/ted/.vscode-server/extensions/f5devcentral.vscode-f5-chariot-1.12.0/out/accWrapper.js:68:28)
	at /home/ted/.vscode-server/extensions/f5devcentral.vscode-f5-chariot-1.12.0/out/extension.js:72:70
	at async /home/ted/.vscode-server/extensions/f5devcentral.vscode-f5-chariot-1.12.0/out/extension.js:69:13]
```

**Comment by mdditt2000** [comment]
@DumpySquare conversion looks good

https://github.com/mdditt2000/f5-appsvcs-acc/blob/master/Github/28/as3-output.json

```
"address_datagroup": {
                "records": [
                    {
                        "key": "1.1.1.1/28",
                        "value": "/"
                    },
                    {
                        "key": "2.2.2.2/32",
                        "value": "/"
                    },
                    {
                        "key": "3.3.3.3/24",
                        "value": "/"
                    }
                ],
                "class": "Data_Group",
                "keyDataType": "string"
```
Looks look good

```
[2021-06-08T20:12:51.950Z] [INFO]: f5.chariot.convert called
[2021-06-08T20:12:51.950Z] [INFO]: f5.chariot.convert text found
[2021-06-08T20:12:52.312Z] [INFO]: ACC METADATA {
  recognized: {
    'ltm data-group internal /partition_1/string-datagroup': { records: { '/api/test/app1': {} }, type: 'string' },
    'ltm data-group internal /partition_2/address_datagroup': {
      records: {
        '1.1.1.1/28': { data: '/' },
        '2.2.2.2/32': { data: '/' },
        '3.3.3.3/24': { data: '/' }
      }
    }
  },
  supported: {
    'ltm data-group internal /partition_1/string-datagroup': { records: { '/api/test/app1': {} }, type: 'string' },
    'ltm data-group internal /partition_2/address_datagroup': {
      records: {
        '1.1.1.1/28': { data: '/' },
        '2.2.2.2/32': { data: '/' },
        '3.3.3.3/24': { data: '/' }
      }
    }
  },
  unSupported: {},
  declarationInfo: {
    classes: { Data_Group: 2 },
    maps: {
      applications: [ '/partition_1/Shared', '/partition_2/Shared' ],
      objects: [
        '/partition_1/Shared/string-datagroup',
        '/partition_2/Shared/address_datagroup'
      ],
      tenants: [ '/partition_1', '/partition_2' ]
    },
    total: 2
  }
}

```
Please confirm before i close it out

**Comment by mdditt2000** [comment]
Broken on Windows 10 environment

```
{
    "class": "ADC",
    "schemaVersion": "3.27.0",
    "id": "urn:uuid:af845e4a-f582-48a6-aa97-53dbbbe45144",
    "label": "Converted Declaration",
    "remark": "Auto-generated by AS3 Config Converter",
    "partition_1": {
        "class": "Tenant",
        "Shared": {
            "class": "Application",
            "template": "shared",
            "string-datagroup": {
                "records": [
                    {
                        "key": "0",
                        "value": ""
                    }
                ],
                "keyDataType": "string",
                "class": "Data_Group"
            }
        }
    },
    "partition_2": {
        "class": "Tenant",
        "Shared": {
            "class": "Application",
            "template": "shared",
            "address_datagroup": {
                "records": [
                    {
                        "key": "0",
                        "value": ""
                    }
                ],
                "keyDataType": "ip",
                "class": "Data_Group"
            }
        }
    }
}
```
Logs
```
[2021-06-08T20:40:58.090Z] [INFO]: ACC Details:  {
  name: 'f5-as3-config-converter',
  author: 'F5 Networks',
  description: 'F5 AS3 Config Converter',
  version: '1.12.0',
  license: 'Apache-2.0',
  repository: 'git+https://github.com/f5devcentral/f5-as3-config-converter.git'
}
[2021-06-08T20:40:58.191Z] [INFO]: f5.chariot.convert called
[2021-06-08T20:40:58.193Z] [INFO]: f5.chariot.convert text found
[2021-06-08T20:40:58.849Z] [INFO]: ACC METADATA {
  recognized: {
    'ltm data-group internal /partition_1/string-datagroup': { records: '{', '/api/test/app1': {}, '}': '', type: 'string' },
    'ltm data-group internal /partition_2/address_datagroup': { records: '{', type: 'ip', '}': '' }
  },
  supported: {
    'ltm data-group internal /partition_1/string-datagroup': { records: '{', '/api/test/app1': {}, '}': '', type: 'string' },
    'ltm data-group internal /partition_2/address_datagroup': { records: '{', type: 'ip', '}': '' }
  },
  unSupported: {},
  declarationInfo: {
    classes: { Data_Group: 2 },
    maps: {
      applications: [ '/partition_1/Shared', '/partition_2/Shared' ],
      objects: [
        '/partition_1/Shared/string-datagroup',
        '/partition_2/Shared/address_datagroup'
      ],
      tenants: [ '/partition_1', '/partition_2' ]
    },
    total: 2
  }
}
[2021-06-08T20:45:08.694Z] [INFO]: f5.chariot.convert called
[2021-06-08T20:45:08.695Z] [INFO]: f5.chariot.convert text found
[2021-06-08T20:45:09.000Z] [INFO]: ACC METADATA {
  recognized: {
    'ltm data-group internal /partition_1/string-datagroup': { records: '{', '/api/test/app1': {}, '}': '', type: 'string' },
    'ltm data-group internal /partition_2/address_datagroup': { records: '{', type: 'ip', '}': '' }
  },
  supported: {
    'ltm data-group internal /partition_1/string-datagroup': { records: '{', '/api/test/app1': {}, '}': '', type: 'string' },
    'ltm data-group internal /partition_2/address_datagroup': { records: '{', type: 'ip', '}': '' }
  },
  unSupported: {},
  declarationInfo: {
    classes: { Data_Group: 2 },
    maps: {
      applications: [ '/partition_1/Shared', '/partition_2/Shared' ],
      objects: [
        '/partition_1/Shared/string-datagroup',
        '/partition_2/Shared/address_datagroup'
      ],
      tenants: [ '/partition_1', '/partition_2' ]
    },
    total: 2
  }
}
```

**Comment by mdditt2000** [comment]
Filed Jira CHARON-315 for PM tracking

**Comment by v-zhuravlev-f5** [comment]
I tested it on windows 10 corporate laptop
![image](https://user-images.githubusercontent.com/66441689/123874207-a3632f80-d8ec-11eb-90c6-f0e0ca7d5b20.png)

ltm data-group internal /partition_1/string-datagroup {
    records {
        /api/test/app1 {}
    }
    type string
}
ltm data-group internal /partition_2/address_datagroup {
    records {
        1.1.1.1/28 {
            data /
        }
        2.2.2.2/32 {
            data /
        }
        3.3.3.3/24 {
            data /
        }
    type ip
    }
}

ltm data-group internal /partition_2/integer_datagroup {
    records {
        1 {
            data 1
        }
        4 {
            data xxx
        }
        5 {
            data 5000
        }
        777 {
            data 7
        }
        96789 {
            data "some data with special !@#${}[]12345"
        }
    }
    type integer
}

C:\Users\zhuravlev\acc\f5-as3-config-converter>node init -c conf.conf
2021-06-29 15:03:33 WARN UNRECOGNIZED LINE:
2021-06-29 15:03:34 INFO 2 BIG-IP objects detected total
2021-06-29 15:03:34 INFO 2 BIG-IP objects recognized by AS3
2021-06-29 15:03:34 INFO 2 BIG-IP objects supported by ACC
2021-06-29 15:03:34 INFO 2 AS3 stanzas generated


2021-06-29 15:10:39 INFO {
    "class": "ADC",
    "schemaVersion": "3.29.0",
    "id": "urn:uuid:348e4488-637b-4052-b71b-a957e069aa62",
    "label": "Converted Declaration",
    "remark": "Auto-generated by AS3 Config Converter",
    "partition_1": {
        "class": "Tenant",
        "Shared": {
            "class": "Application",
            "template": "shared",
            "string-datagroup": {
                "records": [
                    {
                        "key": "/api/test/app1",
                        "value": ""
                    }
                ],
                "keyDataType": "string",
                "class": "Data_Group"
            }
        }
    },
    "partition_2": {
        "class": "Tenant",
        "Shared": {
            "class": "Application",
            "template": "shared",
            "address_datagroup": {
                "records": [
                    {
                        "key": "1.1.1.1/28",
                        "value": "/"
                    },
                    {
                        "key": "2.2.2.2/32",
                        "value": "/"
                    },
                    {
                        "key": "3.3.3.3/24",
                        "value": "/"
                    }
                ],
                "class": "Data_Group",
                "keyDataType": "string"
            },
            "integer_datagroup": {
                "records": [
                    {
                        "key": 1,
                        "value": "1"
                    },
                    {
                        "key": 4,
                        "value": "xxx"
                    },
                    {
                        "key": 5,
                        "value": "5000"
                    },
                    {
                        "key": 777,
                        "value": "7"
                    },
                    {
                        "key": 96789,
                        "value": ""
                    }
                ],
                "keyDataType": "integer",
                "class": "Data_Group"
            }
        }
    }
}

C:\Users\zhuravlev\acc\f5-as3-config-converter>node --version
v14.17.1


C:\Users\zhuravlev\acc\f5-as3-config-converter>npm version
{
  'f5-as3-config-converter': '1.14.0',
  npm: '6.14.13',
  ares: '1.17.1',
  brotli: '1.0.9',
  cldr: '39.0',
  icu: '69.1',
  llhttp: '2.1.3',
  modules: '83',
  napi: '8',
  nghttp2: '1.42.0',
  node: '14.17.1',
  openssl: '1.1.1k',
  tz: '2021a',
  unicode: '13.0',
  uv: '1.41.0',
  v8: '8.4.371.23-node.67',
  zlib: '1.2.11'
}

For the first issue, more details needed on versions for node and npm 

Integer_datagroup did not have a partition in its name, probably copied from tmsh output, not from the config file.

**Comment by DumpySquare** [comment]
## update

I think there is alot going on here.  So, I'll try to break this down and provide an update with the latest v1.13.0 release:

- The windows aspect seems to be resolved when converting line returns to linux based (fix included in v1.13.0 extension released 7/6/2021)
- The integer data-group error was because it didn't have a partition definition (so, no problem there)
- There still seems to be an issue with how values are parsed for data-groups, mainly strings in quotes and with special chars

### example config
```tcl
ltm data-group internal /partition_1/string-datagroup {
    records {
        /api/test/app1 {}
        /api/test/app2 { 
            data something
        }
        /api/test/app3 { 
            data "something in quotes with special stuff!@#${}[]"
        }
        /api/test/app4 { 
            data 1234x5678
        }
    }
    type string
}
ltm data-group internal /partition_2/address_datagroup {
    records {
        1.1.1.1/28 {
            data somedata
        }
        2.2.2.2/32 {
            data "some data with special !@#${}[]12345"
        }
        3.3.3.3/24 {
            data 6534cv
        }
    type ip
    }
}
ltm data-group internal /partition_3/integer_datagroup {
    records {
        1 {
            data 1
        }
        4 {
            data xxx
        }
        5 {
            data 5000
        }
        777 {
            data 7
        }
        96789 {
            data "some data with special !@#${}[]12345"
        }
    }
    type integer
}
```
### output
```json
{
    "class": "ADC",
    "schemaVersion": "3.27.0",
    "id": "urn:uuid:be623a13-ce3c-4678-b296-dea9bae66ef9",
    "label": "Converted Declaration",
    "remark": "Auto-generated by AS3 Config Converter",
    "partition_1": {
        "class": "Tenant",
        "Shared": {
            "class": "Application",
            "template": "shared",
            "string-datagroup": {
                "records": [
                    {
                        "key": "/api/test/app1",
                        "value": ""
                    },
                    {
                        "key": "/api/test/app2",
                        "value": ""
                    },
                    {
                        "key": "}",
                        "value": ""
                    },
                    {
                        "key": "/api/test/app3",
                        "value": ""
                    },
                    {
                        "key": "data \"something in quotes with special stuff!@#$",
                        "value": ""
                    },
                    {
                        "key": "/api/test/app4",
                        "value": ""
                    }
                ],
                "keyDataType": "string",
                "class": "Data_Group"
            }
        }
    },
    "partition_2": {
        "class": "Tenant",
        "Shared": {
            "class": "Application",
            "template": "shared",
            "address_datagroup": {
                "records": [
                    {
                        "key": "1.1.1.1/28",
                        "value": "somedata"
                    },
                    {
                        "key": "2.2.2.2/32",
                        "value": ""
                    },
                    {
                        "key": "3.3.3.3/24",
                        "value": "6534cv"
                    }
                ],
                "class": "Data_Group",
                "keyDataType": "string"
            }
        }
    },
    "partition_3": {
        "class": "Tenant",
        "Shared": {
            "class": "Application",
            "template": "shared",
            "integer_datagroup": {
                "records": [
                    {
                        "key": 1,
                        "value": "1"
                    },
                    {
                        "key": 4,
                        "value": "xxx"
                    },
                    {
                        "key": 5,
                        "value": "5000"
                    },
                    {
                        "key": 777,
                        "value": "7"
                    },
                    {
                        "key": 96789,
                        "value": ""
                    }
                ],
                "keyDataType": "integer",
                "class": "Data_Group"
            }
        }
    }
}
```

### things to note
- app2 string data-group missing value data
- key 3 from string data-group is "}", probably continuation of previous error
- app4 from string data-group has quotes with special chars that doesn't convert
- address data-group value with special chars gets lost
- integer data-group with special chars also gets lost

**do we want to move this to a new issue or continue working here?**

**Comment by v-zhuravlev-f5** [comment]
Looks like all errors related to special characters in values. and not related to Windows or chariot. Would be great if you can create a separate issue related to special chars handling. Thanks.

**Comment by DumpySquare** [comment]
As discussed above, closing this issue to start a fresh one for the special chars.
