### ISSUE TITLE
Received an error while running f5-as3-config-converter

### ISSUE THREAD

**Issue by afreudenreich** [f5devcentral/f5-as3-config-converter#44]
### Environment
 * Application Services Version: f5-as3-config-converter:v1.13.0
 * BIG-IP Version: 14.1.4

### Summary
When running the command without virtual server filter:
```
docker run --rm -v  "$PWD":/app/data f5-as3-config-converter:v1.13.0 -o data/as3_conversion_test_dev.json -u data/as3_conversion_test.ucs
...
2021-07-23 17:24:15 WARN ERROR! DUPLICATE OBJECT NAME DETECTED:
2021-07-23 17:24:15 WARN tlsstats-verf.cybersecurity.ubc.ca exists as both Certificate and Certificate

(node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'properties' of undefined
    at findSchemaDefault (/app/src/removeDefaultValues.js:32:39)
    at /app/src/removeDefaultValues.js:64:33
    at Array.forEach (<anonymous>)
    at matchDefaults (/app/src/removeDefaultValues.js:62:10)
    at /app/src/removeDefaultValues.js:82:20
    at Array.forEach (<anonymous>)
    at findProfiles (/app/src/removeDefaultValues.js:78:10)
    at /app/src/removeDefaultValues.js:80:24
    at Array.forEach (<anonymous>)
    at findProfiles (/app/src/removeDefaultValues.js:78:10)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

When running f5-as3-config-converter with virtual server:
```
docker run --rm -v "$PWD":/app/data f5-as3-config-converter:v1.13.0 -o data/as3_conversion_test_dev.json -u data/as3_conversion_test.ucs -v RMT_LABS.443 -a app_01
...
2021-07-23 17:43:31 WARN ERROR! DUPLICATE OBJECT NAME DETECTED:
2021-07-23 17:43:31 WARN tlsstats-verf.cybersecurity.ubc.ca exists as both Certificate and Certificate

2021-07-23 17:43:31 ERROR Error extracting application. Please email us at solutionsfeedback@f5.com and include the following error:

2021-07-23 17:43:31 ERROR Cannot read property 'Shared' of undefined
```
### Steps To Reproduce
Always.

### Expected Behavior
No error.

### Actual Behavior
Different errors depending on filter parameters.

I ran it from an extracted UCS. If needed I can provide you with the bigip.conf (to F5 email).

**Comment by mdditt2000** [comment]
Reproduced this issue. Created Jira for PM tracking CHARON-405

2021-08-04 17:41:17 WARN ERROR! DUPLICATE OBJECT NAME DETECTED:

**Comment by mdditt2000** [comment]
Resolved! Can be closed out.

**Comment by mdditt2000** [comment]
Received update from Dev: That issue is not yet resolved, so shouldn't be closed: 

Reopened!
