### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by TritiumAE** [f5devcentral/f5-as3-config-converter#48]
### Environment
 * Application Services Version: v1.14.0
 * BIG-IP Version: 15.1.2.1 Build 0.0.10 Point Release 1

### Summary
docker run --rm -v C:\Docker-F5\app\data:/app/data f5-as3-config-converter:v1.14.0 -o data/output.json -c data/input.conf
or
docker run --rm -v C:\Docker-F5\app\data:/app/data f5-as3-config-converter:v1.14.0 -o data/output.json -u data/input.ucs

### Steps To Reproduce
```steps
1. Attempt to run either of the following commands:
docker run --rm -v C:\Docker-F5\app\data:/app/data f5-as3-config-converter:v1.14.0 -o data/output.json -c data/input.conf
or
docker run --rm -v C:\Docker-F5\app\data:/app/data f5-as3-config-converter:v1.14.0 -o data/output.json -u data/input.ucs
```
2. Observe the following error message:
```out
(node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'properties' of undefined
    at findSchemaDefault (/app/src/removeDefaultValues.js:32:39)
    at /app/src/removeDefaultValues.js:64:33
    at Array.forEach (<anonymous>)
    at matchDefaults (/app/src/removeDefaultValues.js:62:10)
    at /app/src/removeDefaultValues.js:83:20
    at Array.forEach (<anonymous>)
    at findProfiles (/app/src/removeDefaultValues.js:79:10)
    at /app/src/removeDefaultValues.js:81:24
    at Array.forEach (<anonymous>)
    at findProfiles (/app/src/removeDefaultValues.js:79:10)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Expected Behavior
Converstion json is created.

### Actual Behavior
Converstion fails.
(node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'properties' of undefined
    at findSchemaDefault (/app/src/removeDefaultValues.js:32:39)
    at /app/src/removeDefaultValues.js:64:33
    at Array.forEach (<anonymous>)
    at matchDefaults (/app/src/removeDefaultValues.js:62:10)
    at /app/src/removeDefaultValues.js:83:20
    at Array.forEach (<anonymous>)
    at findProfiles (/app/src/removeDefaultValues.js:79:10)
    at /app/src/removeDefaultValues.js:81:24
    at Array.forEach (<anonymous>)
    at findProfiles (/app/src/removeDefaultValues.js:79:10)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by mdditt2000** [comment]
I believe this is the same as GitHub Issue: https://github.com/f5devcentral/f5-as3-config-converter/issues/44

Please can you pull the host fix from 
```
docker pull mdditt2000/f5-as3-config-converter:1.15.0-RC2
```

**Comment by TritiumAE** [comment]
Yes, that seems to work successfully now with this rc.  Thanks!

Michael Pearce
________________________________
