### ISSUE TITLE
Error when converting a conf spanning Common and a partition if no objects are to be placed in Common/Shared

### ISSUE THREAD

**Issue by jszczepanski** [f5devcentral/f5-as3-config-converter#55]
### Environment
 * Application Services Version: 1.15 ACC
 * BIG-IP Version: N/A

### Summary
If the uploaded conf file includes objects from both a partition and Common, ACC will raise an error if no objects end up getting placed inside the Common tenant in the resulting declaration.

### Steps To Reproduce
1. Convert following config:
```conf
ltm virtual /tenant1/sample {
    creation-time 2021-09-21:03:26:25
    destination /Common/10.10.10.10:80
    ip-protocol tcp
    last-modified-time 2021-09-21:03:26:25
    mask 255.255.255.255
    profiles {
        /Common/tcp { }
    }
    source 0.0.0.0/0
    translate-address enabled
    translate-port enabled
}
ltm virtual-address /Common/10.10.10.10 {
    address 10.10.10.10
    arp enabled
    inherited-traffic-group true
    mask 255.255.255.255
    traffic-group /Common/traffic-group-1
}
```

2. Observe the following error message:
```out
(node:21) UnhandledPromiseRejectionWarning: TypeError: Error converting input file. Please email us at solutionsfeedback@f5.com and include the following error:

Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at module.exports (/app/src/converter.js:463:38)
    at mainRunner (/app/src/main.js:57:23)
    at main (/app/src/main.js:131:30)
```

**Comment by p-semenov-f5** [comment]
Jira issue created:
https://jira.pdsea.f5net.com/browse/CHARON-467
